<html>
<head>
<link rel="stylesheet" href="app/resources/style.css">
</head>
    <title>MY ATM APP</title>
    <body>
    <div id="app">        
    </body>
    <script src="https://code.jquery.com/jquery-1.8.3.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue"></script>
    <script src="https://unpkg.com/vue@latest/dist/vue.min.js"></script>
    <script src="app/resources/main.js"></script>
    </body>
    </html>
